Focus 297
dittobyte-io/focus-react pull request #11
Opened 2022-11-27 14:03 UTC by rbadamsjr

Currently the Quantity and the data is not connected to a endpoint in  because one has not been made.FOCUS-309 was created to build out the backend in django

2022-12-02 04:04 UTC, rbadamsjr commented
Final change has been pushed and i squashed my commits, if you do Arushi's first I can rebase mine because I think it will be a merge conflict on tha app/api/apiSlice.js files

2022-12-02 20:28 UTC, jsnkle commented on .gitignore
> +./dashboard.css*
this should be a partial so it doesn't compile into css and have to be ignored

2022-12-02 20:29 UTC, jsnkle commented on frontend/package.json
> +    "chart.js": "^3.9.1",
is this library needed in addition to react-chartjs-2?

2022-12-02 20:35 UTC, jsnkle commented on frontend/src/app/api/apiSlice.js
> +	credentials: "include",
Arushi did this a little differently than I did initially and functioning so I merged to master. Let's use hers for now although I think we have an opportunity in the future for some refactoring.

2022-12-02 20:54 UTC, jsnkle commented on frontend/src/pages/Dashboard.js
> +			{/*	<h1 style={{ margin: "0" }}>Dashboard</h1> */}
You can go ahead and remove this altogether... was just a placeholder.

2022-12-02 20:58 UTC, jsnkle commented on frontend/src/app/store.js
> +	middleware: (getDefaultMiddleware) =>
good catch! we definitely need this.

2022-12-02 21:00 UTC, jsnkle requested changes
Let's simplify this naming a bit:
- feature = snapshot/Snapshot.js
- styling = _snapshot.scss
- slice = snaphotSlice.js
- const = snapshotApiSlice

2022-12-03 14:49 UTC, closed without merging

2022-12-03 14:50 UTC, rbadamsjr commented
Closed pr ... making a new one against develop