Focus 312
dittobyte-io/focus-react pull request #21
Opened 2022-12-20 19:48 UTC by ArushiSharma95

Please review the news feature. It shows top 5 news feed on the dashboard.

2022-12-22 03:45 UTC, rbadamsjr commented on frontend/src/components/widget/Widget.js
> +									</a>
We should wrap this in a Map so that we can pass in a array of 'dropdown-items'

2022-12-22 03:47 UTC, rbadamsjr commented on frontend/src/components/widget/Widget.js
> +function Widget(props) {
Change the name of the Widget to something more descriptive .. DataContainerWidget.js

2022-12-22 04:14 UTC, rbadamsjr commented on frontend/src/features/news/NewsList.js
> +	useGetNewsFeedQuery(userId);
This is a overall question about our design for Jason also... should the  'useGetNewsFeedQuery(userId)' be at the NewsList level or the NewsWidget level?

2022-12-22 04:15 UTC, rbadamsjr requested changes
Take a look at my one comment I left..
The major change should be changing the name and using a map for the dropdowns

2022-12-22 04:26 UTC, jsnkle commented on frontend/src/components/widget/Widget.js
> +									</a>
Agreed

2022-12-22 04:29 UTC, jsnkle commented on frontend/src/components/widget/Widget.js
> +function Widget(props) {
Normally I would agree with descriptive function names and variables but in this instance I vote to keep it as Widget.js only because that's what we refer to the ui as and its unique so far. We can refactor if we need to later on.

2022-12-22 04:34 UTC, jsnkle commented on frontend/src/features/news/NewsList.js
> +	useGetNewsFeedQuery(userId);
Good question. My first reaction is to put it in the list... I'll noodle that a bit in the morning when I finish reviewing this PR.

2022-12-29 02:25 UTC, rbadamsjr approved these changes

2022-12-29 02:59 UTC, jsnkle approved these changes

2022-12-29 03:00 UTC, merged