news feature improvements(remove newsWidget + props destructure)
dittobyte-io/focus-react pull request #24
Opened 2023-01-09 22:12 UTC by ArushiSharma95

Please review the minor changes(remove newsWidget + props destructure) in news feature which we have discussed.

2023-01-09 22:43 UTC, jsnkle requested changes

2023-01-09 22:43 UTC, jsnkle commented on frontend/src/components/widget/Widget.js
> +function Widget({name,newsDropdownItems}) {
We can't really name this 'newsDropdownItems' because it will be used for more than news. Let's change to 'dropdownItems' to keep it generic.

2023-01-09 22:43 UTC, jsnkle commented on frontend/src/pages/Dashboard.js
> +	const newsDropdownItems=["Filter","Newsboard","Style","Reset"];
Let's discuss as a team. I'd lean more toward placing this within the Widget component something like this:
`<Widget
	name='Clients'
	dropdownItems={["Filter", "Clientboard", "Style", "Reset"]}
/>`

2023-01-10 20:16 UTC, jsnkle approved these changes

2023-01-13 01:06 UTC, rbadamsjr approved these changes

2023-01-13 17:49 UTC, merged