FOCUS-271a, Created task widget
dittobyte-io/focus-react pull request #25
Opened 2023-01-10 04:28 UTC by rbadamsjr

Please ignore the original FOCUS-271, It was to far out of wack so I created a new branch and add all your comment changes to it.

Please do not delete the old PR i was using that just to insure I had all the code in the new branch...

2023-01-10 18:26 UTC, ArushiSharma95 commented
Really good. Please have a look at few changes that I have suggested above.

2023-01-10 20:14 UTC, jsnkle requested changes

2023-01-10 20:14 UTC, jsnkle commented on frontend/src/features/tasks/TaskList.js
> +								<TaskItem
wrap this in a `<div className="list-group list-group-flush"></div>`

2023-01-11 04:27 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskList.js
> +		<>
Right... onces updated "clicking the checkpox" the mutation will invalid the tags forcing it to update it... so as long as their is more than 5 it will always fetch them

2023-01-11 04:47 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskList.js
> +								<TaskItem
Added..

2023-01-11 04:47 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskItem.js
> +		<div className='list-group-item d-flex align-items-start pb-2'>
resolved

2023-01-11 16:36 UTC, rbadamsjr commented
Updated based on comments

2023-01-12 03:56 UTC, ArushiSharma95 approved these changes
Perfect.

2023-01-12 20:57 UTC, jsnkle approved these changes
Looks good! Thank you!

2023-01-12 20:58 UTC, merged