Focus 311
dittobyte-io/focus-react pull request #27
Opened 2023-01-12 18:21 UTC by ArushiSharma95

FOCUS-311: Improvisation in auth feature

2023-01-12 21:08 UTC, jsnkle reviewed
Just the one question about the middleware...

2023-01-12 21:08 UTC, jsnkle commented on frontend/src/app/store.js
> -		getDefaultMiddleware().concat(apiSlice.middleware),
So do we have to get rid of this from RTK to use the persist feature? Are there any major changes we have to take in approach going this route? Sorry... I should have asked this at our last meeting.

2023-01-13 21:18 UTC, ArushiSharma95 commented on frontend/src/app/store.js
> -		getDefaultMiddleware().concat(apiSlice.middleware),
`middleware: (getDefaultMiddleware) =>
	getDefaultMiddleware({
		serializableCheck: {
			ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
		},
	}).concat(apiSlice.middleware),` 
 No Jason. The difference serializability middleware has now is that we are specifically ignoring all the action types it dispatches. However earlier we were not configuring it to ignore specific action types. Rest all is same here. 
We do have to make few changes in store.js and index.js.... but I don't think there is anything major.

2023-01-20 21:59 UTC, jsnkle approved these changes

2023-01-22 17:24 UTC, rbadamsjr requested changes
Merge focus 254 into this branch when its approved to get the dashboard.js changes back

2023-01-24 23:50 UTC, merged