Focus 254
dittobyte-io/focus-react pull request #29
Opened 2023-01-22 14:58 UTC by rbadamsjr

Created TaskTable, fixed Dashboard.js, TaskList, removed TaskWidget, fixed typo in Client code

2023-01-22 15:32 UTC, jsnkle requested changes
Linter is complaining about your arrow function on line 41 of the TaskList.js expecting a value to be returned. I think you can get away with an anonymous function there. Other comments in the files.

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/pages/Dashboard.js
> +import { TaskList, TasksWidget } from "features/tasks";
I think we can remove TasksWidget here correct?

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +	useUpdateTaskMutation,
doesn't look like useUpdateTaskMutation is being used

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +		taskTableColumns = Object.keys(taskLists[0]);
Where is taskTableColumns being used?

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +					{taskLists.map((row, idx) => {
what is idx being used for? not seeing that in here...

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +											type='button'
Not 100% sure we can use 'type' on an <i/> tag, can you check that please?

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +											type='botton'
Same question as above on type attribute

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +			setTaskId();
I think you need an argument here... can't leave it empty but can set to null if you think it's necessary.

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/features/tasks/_tasks.scss
> +table {
Was bootstrap not doing what you needed? Why the additional styling on table element?

2023-01-22 15:32 UTC, jsnkle commented on frontend/src/pages/Dashboard.js
> +import { Login } from "@microsoft/mgt-react";
Please check your Prettier settings and confirm you have 'useTabs' set to true and 'jsxSingleQuote' set to true

2023-01-22 17:00 UTC, rbadamsjr commented on frontend/src/pages/Dashboard.js
> +import { TaskList, TasksWidget } from "features/tasks";
Done

2023-01-22 17:02 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +	useUpdateTaskMutation,
Done

2023-01-22 17:05 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +		taskTableColumns = Object.keys(taskLists[0]);
Removed

2023-01-22 17:06 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +					{taskLists.map((row, idx) => {
Originally used the idx to give the <td> a unique key.. but don't need it anymore

2023-01-22 17:08 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +											type='button'
No problem...

2023-01-22 17:08 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +											type='botton'
removed

2023-01-22 17:10 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +			setTaskId();
Fixed ... also removed console.log()

2023-01-22 17:13 UTC, rbadamsjr commented on frontend/src/features/tasks/_tasks.scss
> +table {
I wanted more space between the checkbox and the label

2023-01-22 17:15 UTC, rbadamsjr commented on frontend/src/pages/Dashboard.js
> +import { Login } from "@microsoft/mgt-react";
Set it to true

2023-01-23 22:24 UTC, jsnkle commented on frontend/src/features/tasks/_tasks.scss
> +table {
Sorry... I'm referring to the table element. You've added a width, layout, overflow and border attributes. Lines 19-23 and 36-40.

2023-01-24 04:52 UTC, ArushiSharma95 approved these changes
Looks good.

2023-01-24 23:24 UTC, jsnkle approved these changes

2023-01-24 23:24 UTC, merged