Focus 330
dittobyte-io/focus-react pull request #40
Opened 2023-02-09 00:43 UTC by rbadamsjr

2023-02-09 13:55 UTC, jsnkle requested changes

2023-02-09 13:55 UTC, jsnkle commented on frontend/src/app/app.css
> +  width: -moz-min-content;
Please remove this file from the PR. Line's 118 and 119 should not be in this file. You can update your copy of app.css with a copy/paste from develop branch and it should no longer flag this as a changed file.

2023-02-09 13:55 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
> +import { store } from "../../app/store";
Use absolute imports for components:
`import { store } from "app/store"`

2023-02-09 13:55 UTC, jsnkle commented on frontend/src/features/tasks/TaskTable.js
>  	const DELETE_DIALOG_MESSAGE = "Are you sure you want to delete this task?";
I think we need to include the task title in the message here.

2023-02-09 13:55 UTC, jsnkle commented on frontend/src/features/tasks/TaskItem.js
> +import { SimpleProvider } from "@microsoft/mgt-element";
This import doesn't look like it's being used here...

2023-02-09 13:55 UTC, jsnkle commented on frontend/src/features/tasks/TaskItem.js
> +	const [taskId, setTaskId] = useState(id);
Do you need to useState here? If you're setting the initial value to the id prop but then never updating via setTaskId you can probably just pass the id prop into the updateHandler directly.

Also take a look at line 23 where you have the input element id='flexCheckDefault'. You have to use something unique for an any element id on a page and the way this is written each task will have the same one.

2023-02-09 16:41 UTC, ArushiSharma95 reviewed
It looks good to me. I have requested few minor changes above.

2023-02-09 16:41 UTC, ArushiSharma95 commented on frontend/src/features/impacts/ImpactsSnapshot.js
> -		useGetConsultantImpactsQuery(consultantId);
Once I login and go to the consultant dashboard. If I add more impacts, it will not display it on refresh.  refetchOnMountOrArgChange needs to be set true.

2023-02-09 16:41 UTC, ArushiSharma95 commented on frontend/src/features/initiatives/InitiativesSnapshot.js
refetchOnMountOrArgChange needs to be set true.

2023-02-09 16:41 UTC, ArushiSharma95 commented on frontend/src/features/initiatives/InitiativesSnapshot.js
> +	if (store.getState().auth.userData === null) userId = 0;
I think we need to decide if we will call it userId or consultantId. I will vote for consultantId because we are currently doing it for consultant.  User id becomes more generic. And we will need to change it later. 
@rbadamsjr @jsnkle What do you think?

2023-02-10 00:10 UTC, rbadamsjr commented on frontend/src/app/app.css
> +  width: -moz-min-content;
Copied in

2023-02-10 00:11 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskTable.js
> +import { store } from "../../app/store";
Done..

2023-02-10 00:12 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskItem.js
> +import { SimpleProvider } from "@microsoft/mgt-element";
Sorry, had copied some code in... but removed

2023-02-10 00:20 UTC, rbadamsjr commented on frontend/src/features/tasks/TaskItem.js
> +	const [taskId, setTaskId] = useState(id);
Fixed...

2023-02-10 00:23 UTC, rbadamsjr commented on frontend/src/features/impacts/ImpactsSnapshot.js
> -		useGetConsultantImpactsQuery(consultantId);
Fixed

2023-02-10 00:23 UTC, rbadamsjr commented on frontend/src/features/initiatives/InitiativesSnapshot.js
Fixed

2023-02-10 00:24 UTC, rbadamsjr commented on frontend/src/features/initiatives/InitiativesSnapshot.js
> +	if (store.getState().auth.userData === null) userId = 0;
I like it as consultantId but I would change it to myConsultantId

2023-02-10 01:16 UTC, jsnkle commented on frontend/src/features/initiatives/InitiativesSnapshot.js
> +	if (store.getState().auth.userData === null) userId = 0;
Well... we will have roles at some point and whomever is logged in may not be a consultant.  If I'm a manager with several consultants under me this snapshot should show all Initiatives from all consultants under me. At the same time... I may want to see a report on some other page filtered by consultant. I think for the dashboard it makes sense for it to be the generic userId. Let's leave it as is for now and discuss further down the road.

2023-02-10 01:27 UTC, jsnkle requested changes
All looks good you just missed that one little spot in the TaskItem.js

2023-02-10 01:27 UTC, jsnkle commented on frontend/src/features/tasks/TaskItem.js
> +							id={id}
Cool here but you forgot the htmlFor value in the label on line 25

2023-02-10 19:52 UTC, jsnkle approved these changes

2023-02-10 19:55 UTC, ArushiSharma95 approved these changes

2023-02-10 19:56 UTC, merged