Focus 359 Focus Score
dittobyte-io/focus-react pull request #42
Opened 2023-03-12 03:25 UTC by rbadamsjr

Note: I left comment code in this PR.. just in case any of you two find an error.. but before the merge... I or one of you will create a task to remove comments...

2023-03-17 19:24 UTC, ArushiSharma95 reviewed
It looks good to me in terms of functionality. I have tried various test cases. It is working as per the expectation. There are few points that needs to be discussed in the team meeting. Rest all looks good.

2023-03-17 19:24 UTC, ArushiSharma95 commented on frontend/src/features/focus-score/Focusscore.js
We need to use Pascal case for naming the components.

2023-03-17 19:24 UTC, ArushiSharma95 commented on frontend/src/features/focus-score/Focusscore.js
> +		isLoading,
It is never used.

2023-03-17 19:24 UTC, ArushiSharma95 commented on frontend/src/features/focus-score/Focusscore.js
> +			var targetAverage;
Prefer usage of const here instead of var

2023-03-17 19:24 UTC, ArushiSharma95 commented on frontend/src/features/focus-score/Focusscore.js
Th focus score goes down to zero here if there is no data for a particular month. Need to discuss it once within the team.

2023-03-17 22:18 UTC, jsnkle requested changes

2023-03-17 22:18 UTC, jsnkle commented on frontend/src/features/focus-score/FocusScore.js
> +				targetValues: new Array(),
Instead of:
`currentValues: new Array()`
you can just do:
`currentValues: []`

same on line 136

2023-03-18 23:04 UTC, jsnkle requested changes
The only real thing that needs edited is the 'var' usage in the FocusScore.js file. The other two things I mentioned... your way works fine but I gave a suggestion for a refactor.

2023-03-19 01:50 UTC, jsnkle submitted a review, later dismissed

2023-03-19 02:30 UTC, jsnkle approved these changes

2023-03-20 16:06 UTC, ArushiSharma95 approved these changes
Looks good.

2023-03-20 17:48 UTC, merged