Focus 247 f
dittobyte-io/focus-react pull request #45
Opened 2023-03-24 18:58 UTC by ArushiSharma95

Goal Detail Implementation.

2023-03-24 22:51 UTC, jsnkle requested changes
Please put something on my calendar Monday to have you demo this. This was a lot of work, good job. Also, please put a tech debt ticket in the backlog to take care of some the duplication of code we have in the __ByGoalSnapshot.js files but nothing to worry about right now.

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/app/App.js
> +						<Route path='goal/:id' element={<Goal />} />
path should be 'goals' plural not singular

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/app/api/apiSlice.js
> +	baseUrl: "http://127.0.0.1:8000",
don't forget to change this back to prod

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/features/goals/GoalDetail.js
> +				return "No Attatchments";
Your default should be one of your previously defined cases not another option. In this instance it should be GoalHierarchy.

I'm foggy on the status of the Attachments component. Is this what you mentioned in the stand up on Friday because my brain heard "comments" but now doubting myself.

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/features/goals/GoalsTable.js
> +									<Link to={`/goal/${row.id}`} state={{ goalId: `${row.id}` }}>
be sure to update this path to 'goals' as well when you change it in app.js

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/features/impacts/BarGraph.js
> +function BarGraph({ initiativeId, key }) {
I think you can remove 'key' here?

2023-03-24 22:51 UTC, jsnkle commented on frontend/src/features/impacts/Chart.js
> +function Chart({ key, labels, data1, data2, title }) {
doesn't look like 'key' and 'title' are being used?

2023-03-24 22:51 UTC, jsnkle commented on package.json
> +    "jodit-react": "^1.3.39"
You can remove jodit-react from this package.json since it's for the proxy server only needs to be in the frontend one.

2023-03-27 21:34 UTC, jsnkle approved these changes
just check me on my note to you about syntax for default in the switch statement and take care of the package-lock.json file and you should be good to go pending Roland's review.

2023-03-27 22:57 UTC, rbadamsjr commented on frontend/src/app/api/apiSlice.js
> +	// baseUrl: "http://127.0.0.1:8000",
Remove the commented code

2023-03-27 23:13 UTC, rbadamsjr commented on frontend/src/features/goals/GoalDetail.js
> +	const [inventoryId, setInventoryId] = useState(1);
Why the default value?

2023-03-27 23:56 UTC, rbadamsjr approved these changes

2023-03-27 23:56 UTC, rbadamsjr commented on frontend/src/features/goals/GoalHierarchy.js
> +	if (!isSuccess || !data.data) {
Why didn’t you use isError

2023-03-27 23:56 UTC, rbadamsjr commented on frontend/src/features/impacts/BarGraph.js
> +				currentValue[k] = impactHistory[i].current_value;
Wouldn’t a forEach be better?

2023-03-28 00:07 UTC, jsnkle approved these changes

2023-03-28 00:08 UTC, merged